gitblog:
  links:
    github: "https://github.com/idioglossia/git-blog"
    features: "https://github.com/idioglossia/git-blog"
  config:
    init: false
    dbPath: "db/"
    reads: 10
    writes: 5
logging:
  file:
    name: gitblog.log
  level:
    ROOT: info
server:
  port: 8083
spring:
  messages:
    basename: lang/res